Add missing @types/lodash
When try to compile typescript under ./types/example directory,
it's throw an error:

```console
$ ./node_modules/.bin/tsc ./types/examples/as_promises.ts
node_modules/@types/bluebird/index.d.ts(622,33): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(622,72): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(822,39): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(822,78): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(826,27): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(826,65): error TS2304: Cannot find name 'Map'.
```

It happen because of missing `@types/lodash` in dependencies block.